const configuration = {
	extends: ['@commitlint/config-conventional'],
	rules: {
		'scope-enum': [
			2,
			'always',
			[
				'api',
				'assets',
				'authentication',
				'components',
				'composables',
				'config',
				'constants',
				'core',
				'dependencies',
				'directives',
				'documentation',
				'infrastructure',
				'interfaces',
				'internationalization',
				'layout',
				'locales',
				'middlewares',
				'mocks',
				'pages',
				'plugins',
				'public',
				'readme',
				'release',
				'security',
				'services',
				'stores',
				'styles',
				'testing',
				'todo',
				'types',
				'ui',
				'utils',
				'validations',
				'views',
				'vscode',
			],
		],
		'subject-case': [2, 'always', ['lower-case']],
	},
};

export default configuration;
